- hosts: server1
  become: yes
  vars:
    artifactory_download_url: "https://releases.jfrog.io/artifactory/jfrog-artifactory-oss-release/com/jfrog/artifactory/oss/jfrog-artifactory-oss/7.3.2/jfrog-artifactory-oss-7.3.2-linux.tar.gz"
  roles:
    - role: eugene_krivosheyev.artifactory
      artifactory_port: 8081
      artifactory_ui_port: 8082
      artifactory_username: admin
      artifactory_password: P@ssw0rd

